live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x7f7f7f"
blue = "0x5c5cff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.normal]
black = "0x000000"
blue = "0x0000ee"
cyan = "0x00cdcd"
green = "0x00cd00"
magenta = "0xcd00cd"
red = "0xcd0000"
white = "0xe5e5e5"
yellow = "0xcdcd00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[cursor]
style = "Underline"

[font]
size = 11

[font.bold]
family = "IntelOne Mono"
style = "Bold"

[font.bold_italic]
family = "IntelOne Mono"
style = "Bold Italic"

[font.italic]
family = "IntelOne Mono"
style = "Italic"

[font.normal]
family = "IntelOne Mono"

[window]
blur = true
opacity = 0.8
