live_config_reload: true

window:
  opacity: 0.8
  blur: true

font:
  normal:
    family: IntelOne Mono
  bold:
    family: IntelOne Mono
    style: Bold
  italic:
    family: IntelOne Mono
    style: Italic
  bold_italic:
    family: IntelOne Mono
    style: Bold Italic
  size: 11

draw_bold_text_with_bright_colors: true

# XTerm's default colors
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xcd0000'
    green:   '0x00cd00'
    yellow:  '0xcdcd00'
    blue:    '0x0000ee'
    magenta: '0xcd00cd'
    cyan:    '0x00cdcd'
    white:   '0xe5e5e5'

  # Bright colors
  bright:
    black:   '0x7f7f7f'
    red:     '0xff0000'
    green:   '0x00ff00'
    yellow:  '0xffff00'
    blue:    '0x5c5cff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'

cursor:
  style:
    shape: Underline
    blinking: off
    unfocused_hallow: true
